# fly.toml app configuration file generated for school-exam on 2023-06-05T13:01:04+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "school-exam"
kill_signal = "SIGINT"
kill_timeout = 50
primary_region = "sin"
#restart = "manual"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
#  tcp_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  auto_start_machines = false
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 3
    timeout = "2s"
